{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/jschaf/pylint-flask",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "GPL 2",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pylint-flask/pylint-flask-0.4.tar.gz",
    "subdirs": [
      "osx-64"
    ],
    "summary": "pylint-flask is a Pylint plugin to aid Pylint in recognizing and understanding errors caused when using Flask",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "0.4"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main"
  ],
  "package": "pylint-flask-0.4-py34_0.tar.bz2",
  "repodata": {
    "build": "py34_0",
    "build_number": 0,
    "depends": [
      "astroid >=1.0",
      "logilab-common >=0.60.0",
      "pylint >=1.0",
      "pylint-plugin-utils >=0.2.1",
      "python 3.4*"
    ],
    "license": "GPL 2",
    "md5": "cd4ab981899ad5233bc7a3034d1ed544",
    "name": "pylint-flask",
    "sha256": "9c3cdc5344f8b80c498e705349df0c0dd07ce01f2fef5f8cce937cff4b876ce8",
    "size": 4481,
    "subdir": "osx-64",
    "version": "0.4"
  },
  "repodata_version": 1,
  "subdir": "osx-64",
  "url": "https://conda.anaconda.org/conda-forge/osx-64/pylint-flask-0.4-py34_0.tar.bz2"
}