{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/landscapeio/pylint-celery",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "GPL 2",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pylint-celery/pylint-celery-0.3.tar.gz",
    "subdirs": [
      "osx-64"
    ],
    "summary": "pylint-celery is a Pylint plugin to aid Pylint in recognising and understandingerrors caused when using the Celery library",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "0.3"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main",
    "cf202003"
  ],
  "package": "pylint-celery-0.3-py27_0.tar.bz2",
  "repodata": {
    "build": "py27_0",
    "build_number": 0,
    "depends": [
      "astroid >=1.0",
      "pylint >=1.0",
      "pylint-plugin-utils >=0.2.1",
      "python 2.7*"
    ],
    "license": "GPL 2",
    "md5": "bc422b35176dfaee303f16dbeb840169",
    "name": "pylint-celery",
    "sha256": "50703ce8d803b7cfba9eea0dc994cb848b7b99ad5845e4475d7ff84156f70f62",
    "size": 2609,
    "subdir": "osx-64",
    "version": "0.3"
  },
  "repodata_version": 1,
  "subdir": "osx-64",
  "url": "https://conda.anaconda.org/conda-forge/osx-64/pylint-celery-0.3-py27_0.tar.bz2"
}