{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-1.6.0.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1560568116,
    "version": "1.6.0"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "cf202003",
    "main"
  ],
  "package": "pytest-faulthandler-1.6.0-py37_0.tar.bz2",
  "repodata": {
    "build": "py37_0",
    "build_number": 0,
    "depends": [
      "pytest",
      "python >=3.7,<3.8.0a0"
    ],
    "license": "MIT",
    "md5": "ae192bf7987176034e929efe1907e605",
    "name": "pytest-faulthandler",
    "sha256": "52a41a689ac58aa250ac80a725628c77076ddcd3d7f73986fcad5384eabdf812",
    "size": 8006,
    "subdir": "linux-64",
    "timestamp": 1560568116813,
    "version": "1.6.0"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://github.com/regro/releases/releases/download/linux-64/pytest-faulthandler-1.6.0-py37_0.tar.bz2/pytest-faulthandler-1.6.0-py37_0.tar.bz2"
}