{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://pypi.org/project/django-axes/",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/d/django-axes/django-axes-5.19.0.tar.gz",
    "subdirs": [
      "noarch"
    ],
    "summary": "django-axes, User lockout in django apps.",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1623966041,
    "version": "5.19.0"
  },
  "channeldata_version": 1,
  "feedstock": "django-axes-feedstock",
  "labels": [
    "main"
  ],
  "package": "django-axes-5.19.0-pyhd8ed1ab_0.tar.bz2",
  "repodata": {
    "build": "pyhd8ed1ab_0",
    "build_number": 0,
    "depends": [
      "django >=2.2",
      "django-ipware >=3,<4",
      "python >=3.6",
      "setuptools"
    ],
    "license": "MIT",
    "md5": "00f47f8d1b3fd54eceea7c235e2105e9",
    "name": "django-axes",
    "noarch": "python",
    "sha256": "315c0f4e569bbb64074dcf0328221df6a7582fb8c43886358311796a4371f62a",
    "size": 38577,
    "subdir": "noarch",
    "timestamp": 1623966041022,
    "version": "5.19.0"
  },
  "repodata_version": 1,
  "subdir": "noarch",
  "url": "https://github.com/conda-forge/releases/releases/download/noarch/django-axes-5.19.0-pyhd8ed1ab_0.tar.bz2/django-axes-5.19.0-pyhd8ed1ab_0.tar.bz2"
}