{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/landscapeio/pylint-celery",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "GPL 2",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pylint-celery/pylint-celery-0.3.tar.gz",
    "subdirs": [
      "win-64"
    ],
    "summary": "pylint-celery is a Pylint plugin to aid Pylint in recognising and understandingerrors caused when using the Celery library",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "0.3"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main"
  ],
  "package": "pylint-celery-0.3-py35_0.tar.bz2",
  "repodata": {
    "build": "py35_0",
    "build_number": 0,
    "depends": [
      "astroid >=1.0",
      "pylint >=1.0",
      "pylint-plugin-utils >=0.2.1",
      "python 3.5*"
    ],
    "license": "GPL 2",
    "md5": "3bf709d46d6c8355f1d9a938474da119",
    "name": "pylint-celery",
    "sha256": "8fde911a6ff2f0aa179d7476edf2bcf65b0e93931ea77d9a7f62d97b3e39b28e",
    "size": 183452,
    "subdir": "win-64",
    "version": "0.3"
  },
  "repodata_version": 1,
  "subdir": "win-64",
  "url": "https://conda.anaconda.org/conda-forge/win-64/pylint-celery-0.3-py35_0.tar.bz2"
}