{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-1.3.1.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "1.3.1"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "cf202003",
    "main",
    "cf201901"
  ],
  "package": "pytest-faulthandler-1.3.1-py27_0.tar.bz2",
  "repodata": {
    "build": "py27_0",
    "build_number": 0,
    "depends": [
      "pytest",
      "python 2.7*"
    ],
    "license": "MIT",
    "md5": "8dd9a32d9947e050b509119a0ed0125b",
    "name": "pytest-faulthandler",
    "sha256": "86463d1a643136e751f9a865b09c122f426e9b761936f63559f68e56dbca862a",
    "size": 4544,
    "subdir": "linux-64",
    "version": "1.3.1"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://github.com/regro/releases/releases/download/linux-64/pytest-faulthandler-1.3.1-py27_0.tar.bz2/pytest-faulthandler-1.3.1-py27_0.tar.bz2"
}