{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-rerunfailures",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MPL-2.0",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-rerunfailures/pytest-rerunfailures-10.0.tar.gz",
    "subdirs": [
      "noarch"
    ],
    "summary": "pytest plugin to re-run tests to eliminate flaky failures",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1622121487,
    "version": "10.0"
  },
  "channeldata_version": 1,
  "feedstock": "pytest-rerunfailures-feedstock",
  "labels": [
    "main"
  ],
  "package": "pytest-rerunfailures-10.0-pyhd8ed1ab_0.tar.bz2",
  "repodata": {
    "build": "pyhd8ed1ab_0",
    "build_number": 0,
    "depends": [
      "pytest >=5.0",
      "python >=3.5",
      "setuptools >=40.0"
    ],
    "license": "MPL-2.0",
    "license_family": "OTHER",
    "md5": "823b5c5d5a8ee6f434a81870ea55a345",
    "name": "pytest-rerunfailures",
    "noarch": "python",
    "sha256": "bf3d939019ccbf5a1bc969eb44806509c2c7ea2ecbbdde44a58d203ce51053fc",
    "size": 11894,
    "subdir": "noarch",
    "timestamp": 1622121487876,
    "version": "10.0"
  },
  "repodata_version": 1,
  "subdir": "noarch",
  "url": "https://github.com/conda-forge/releases/releases/download/noarch/pytest-rerunfailures-10.0-pyhd8ed1ab_0.tar.bz2/pytest-rerunfailures-10.0-pyhd8ed1ab_0.tar.bz2"
}