{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": "https://github.com/LuminosoInsight/python-ftfy",
    "doc_source_url": null,
    "doc_url": "http://ftfy.readthedocs.io/",
    "home": "https://github.com/LuminosoInsight/python-ftfy/",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/f/ftfy/ftfy-5.1.1.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "Fixes some problems with Unicode text after the fact",
    "tags": null,
    "text_prefix": true,
    "timestamp": 0,
    "version": "5.1.1"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "cf202003"
  ],
  "package": "ftfy-5.1.1-py35_0.tar.bz2",
  "repodata": {
    "build": "py35_0",
    "build_number": 0,
    "depends": [
      "python 3.5*",
      "setuptools",
      "wcwidth"
    ],
    "license": "MIT",
    "md5": "d9659c37b30284decdf2d1b530e1d044",
    "name": "ftfy",
    "sha256": "e833825797e3cbc213f09208614bc615c89936fd960831d23a42f19ff299582a",
    "size": 50639,
    "subdir": "linux-64",
    "version": "5.1.1"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://conda.anaconda.org/conda-forge/label/cf202003/linux-64/ftfy-5.1.1-py35_0.tar.bz2"
}