{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": "https://github.com/Pylons/weberror",
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/Pylons/weberror",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/W/WebError/WebError-0.13.1.tar.gz",
    "subdirs": [
      "noarch"
    ],
    "summary": "Web Error handling and exception catching\\",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1570041233,
    "version": "0.13.1"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main",
    "cf202003"
  ],
  "package": "weberror-0.13.1-py_0.tar.bz2",
  "repodata": {
    "build": "py_0",
    "build_number": 0,
    "depends": [
      "paste >=1.7.1",
      "pygments",
      "python",
      "tempita",
      "webob"
    ],
    "license": "MIT",
    "license_family": "MIT",
    "md5": "4503a353642b13c2d8e56de053e045a0",
    "name": "weberror",
    "noarch": "python",
    "sha256": "03f5f4b5e5d4224c0119bf8e5efafb0ceffab1f8cc93fed19b58c82a8b428469",
    "size": 73115,
    "subdir": "noarch",
    "timestamp": 1570041233311,
    "version": "0.13.1"
  },
  "repodata_version": 1,
  "subdir": "noarch",
  "url": "https://conda.anaconda.org/conda-forge/noarch/weberror-0.13.1-py_0.tar.bz2"
}