{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-1.4.1.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "1.4.1"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "cf202003"
  ],
  "package": "pytest-faulthandler-1.4.1-py27_0.tar.bz2",
  "repodata": {
    "build": "py27_0",
    "build_number": 0,
    "depends": [
      "faulthandler",
      "pytest",
      "python 2.7*"
    ],
    "license": "MIT",
    "md5": "d730da655d3e5f15a112bf2d1f0d25d2",
    "name": "pytest-faulthandler",
    "sha256": "c285225a9ba88f488f7d2b6b0996dabeb9628b01ce2b4d6176c52514ba3f7bcc",
    "size": 8174,
    "subdir": "linux-64",
    "version": "1.4.1"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://conda.anaconda.org/conda-forge/label/cf202003/linux-64/pytest-faulthandler-1.4.1-py27_0.tar.bz2"
}