{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/testing-cabal/traceback2",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "PSF 2.0",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/t/traceback2/traceback2-1.4.0.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "Backports of the traceback module",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "1.4.0"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "cf202003"
  ],
  "package": "traceback2-1.4.0-py34_0.tar.bz2",
  "repodata": {
    "build": "py34_0",
    "build_number": 0,
    "depends": [
      "linecache2",
      "python 3.4*",
      "six"
    ],
    "license": "PSF 2.0",
    "md5": "826c7ccae3e77070e395169c820d99ef",
    "name": "traceback2",
    "sha256": "ed2aa0b7e910f62cbaa25000635c59d5c839d01b4458ae456d987c4a7ae3b799",
    "size": 29003,
    "subdir": "linux-64",
    "version": "1.4.0"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://conda.anaconda.org/conda-forge/label/cf202003/linux-64/traceback2-1.4.0-py34_0.tar.bz2"
}